export default [
  {
    cols: 2,
    name: 'Buddy Rich',
    image: 'http://www.drummerworld.com/pics/drumpics34/buddyrich500999.jpg',
    rows: 3,
    years: 'September 30, 1917 - April 2, 1987',
  },
  {
    cols: 3,
    name: 'Tony Williams',
    image: 'http://drummerworld.com/drummerworld/tonywilliams840uuper.jpg',
    rows: 3,
    years: 'December 12, 1945 - February 23, 1997',
  },
  {
    cols: 2,
    name: 'Steve Gadd',
    image: 'http://www.drummerworld.com/drummerworld2/stevegaddbio550.jpg',
    rows: 2,
    years: 'b. April 9, 1945',
  },
  {
    cols: 1,
    name: 'Sheila E.',
    image: 'http://www.drummerworld.com/pics/drum/dpa24/SheilaE3.jpg',
    rows: 2,
    years: 'b. December 12, 1957',
  },
  {
    cols: 1,
    name: 'Jojo Mayer',
    image: 'http://www.drummerworld.com/drummerworld2/jojomayer550kjhg.jpg',
    rows: 2,
    years: 'b. January 18, 1963',
  },
  {
    cols: 1,
    name: 'Ahmir "Questlove" Thompson',
    image: 'http://www.drummerworld.com/drummerworld/ahmirquestolvethompson160.jpg',
    rows: 2,
    years: 'b. January 20, 1971',
  },
  {
    cols: 1,
    name: 'Dave Grohl',
    image: 'http://www.drummerworld.com/pics/drumpics31/davegrohlharley1.jpg',
    rows: 2,
    years: 'b. January 14, 1969',
  },
  {
    cols: 2,
    name: 'Horacio "El Negro" Hernandez',
    image: 'http://www.drummerworld.com/pics/drumpics34/horatiohernandez550987.jpg',
    rows: 2,
    years: 'b. April 24, 1963',
  },
  {
    cols: 3,
    name: 'Larnell Lewis',
    image: 'http://www.drummerworld.com/drummerworld/larnelllewis35011.jpg',
    rows: 4,
    years: 'b. March 22, 1984',
  },
  {
    cols: 2,
    name: 'Nate Smith',
    image: 'http://www.drummerworld.com/drummerworld/natesmithcarlosibanez.jpg',
    rows: 3,
    years: 'b. December 14, 1974',
  },
  {
    cols: 2,
    name: 'Anika Nilles',
    image: 'http://www.drummerworld.com/drummerworld/anikanillesnorberts.jpg',
    rows: 2,
    years: 'b. May 29, 1983',
  },
  {
    cols: 2,
    name: 'Zakir Hussain',
    image: 'http://drummerworld.com/pics/drum12/zakir_hussain2.jpg',
    rows: 2,
    years: 'b. March 9, 1951',
  },
  {
    cols: 3,
    name: 'Cindy Blackman Santana',
    image: 'http://www.drummerworld.com/drummerworld/cindyblackman350kjghh.jpg',
    rows: 4,
    years: 'b. November 18, 1959',
  },
];
